### ISSUE TITLE
Question: Validation Ground Truth JSON Format

### ISSUE THREAD

**Issue by michaelhsmart** [jskinn/rvchallenge-starter-kit#2]
I'm having some trouble interpreting the json ground truth detections for the validation data set, as the json file looks a bit different from what I was expecting.

For example, the first few entries of `validation_data/ground_truth/000000/labels.json` look like:
```
{"005171": {
            "_metadata": {
                        "mask_name": "3813.masks.png"
                        },
            "000046":   {
                        "mask_id": 1, "bounding_box": [219, 42, 223, 48], "class": "bottle", "num_pixels": 19
                        },
            "000131":  {"mask_id": 2, "bounding_box": [482, 0, 564, 57], "class": "potted plant", "num_pixels": 2104
                        }
            },
"004500": {
            "000127": {
                        "mask_id": 1, "bounding_box": [612, 58, 639, 369], "class": "oven", "num_pixels": 8338
                      },
          "_metadata": {
                      "mask_name": "3391.masks.png"
                      }
          },
```

How do the top level keys (like "005171" or "004500" above) map to specific entries in the dataset?

I guess I can extract the corresponding image name from the `_metadata: 'XXXX.masks.png'` entry but this doesn't seem to match with what [Submission Format](https://github.com/jskinn/rvchallenge-starter-kit#submission-format) or [Validation Data](https://github.com/jskinn/rvchallenge-starter-kit#validation-data) indicate about the format in the readme, so I am slightly confused.

Thanks!

**Comment by jskinn** [comment]
The ground truth is a little different to the submission format, they're different things and contain different data.
Ground truth has binary pixel-masks for each object in each image, while the submission needs to provide spatial uncertainty for each pixel using boxes with corner covariances, and doesn't have mask images.

The ground truth labels you've posted here are read by the ground truth loader (see [https://github.com/jskinn/rvchallenge-evaluation/blob/master/gt_loader.py](https://github.com/jskinn/rvchallenge-evaluation/blob/master/gt_loader.py)).
The top level keys are the image name without the file extension, so "004500" contains the ground truth for frame "frames/004500.png", which is the 4501st image in the sequence (the first image is "000000").
They're out of order because python dictionaries are unordered, and it doesn't really need to be human readable.
For a more detailed explanation of the ground truth, have a look at the comments in `gt_loader.py` linked above, particularly the `read_sequence` function.

Submissions are in a different format, which is read by the submission loader (see [https://github.com/jskinn/rvchallenge-evaluation/blob/master/submission_loader.py](https://github.com/jskinn/rvchallenge-evaluation/blob/master/submission_loader.py)).
If in doubt, you can use the code in `submission_builder.py` to generate a file in the correct format, and can verify any submission file you make using `submission_validator.py`.

**Comment by jskinn** [comment]
(whoops, I should have let you close it when your questions were answered)

**Comment by michaelhsmart** [comment]
> The top level keys are the image name without the file extension

Bingo, that's what I needed. The comments linked in `gt_loader.py` are really helpful too.

Thanks!
